name: color_discovery
description: A Flutter color discovery application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.5.1

 
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  lottie: ^3.1.0
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0 
  image_picker: ^1.0.8 
  palette_generator: ^0.3.3+3
  flutter_colorpicker: ^1.0.3
  share_plus: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1
  build_runner: ^2.4.9

  flutter_lints: ^3.0.0  

flutter:
  uses-material-design: true
